project:
  type: website

website:
  title: "Scratching Post Interactive"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hearthstone-balance.ipynb
        text: Hearthstone Balance
      - href: csprosjoes.qmd
        text: CS Bros vs Pros
      - href: cs-economy.qmd
        text: Novelty in the CS Economy
      - href: photography.qmd
        text: Film Photography

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1400px
      margin-width: 300px
    resources:
      - resume.pdf
      - cs-economy-report.pdf
      - cs-coordination-report.pdf